import { useEffect, useState } from 'react'
import { store } from '../../wailsjs/go/models'
import * as API from '../../wailsjs/go/main/App'

// ---- ApplicationSet guard ------------------------------------------------------

function covered(g: store.AppSetGuard, path: string) {
  if (g.applicationsSync === 'create-only' || g.applicationsSync === 'create-delete') return true
  return (g.ignored ?? []).some((p) => {
    const ptr = p.startsWith('.') ? p.replace(/\./g, '/').replace(/\[\]/g, '') : p
    return path.startsWith(ptr) || ptr.startsWith(path)
  })
}

// Warns when the owning ApplicationSet will overwrite a manual change.
export function GuardBanner({ guard, path, what }: { guard: store.AppSetGuard | null; path: string; what: string }) {
  if (!guard?.appSet) return null
  if (covered(guard, path)) {
    return (
      <div className="alert ok" style={{ marginBottom: 10 }}>
        Generated by ApplicationSet <b>{guard.appSet}</b>, which ignores changes to <code>{path}</code>
        {guard.applicationsSync ? ` (applicationsSync: ${guard.applicationsSync})` : ''} — your change will stick.
      </div>
    )
  }
  return (
    <div className="alert" style={{ marginBottom: 10, background: 'var(--warning-bg)', color: 'var(--warning-fg)' }}>
      <b>Heads-up:</b> this app is generated by ApplicationSet <b>{guard.appSet}</b>. Its controller re-applies the template
      and will <b>revert {what}</b> within seconds. To keep it, change the ApplicationSet (or Git), or add to the ApplicationSet:
      <pre className="code-block" style={{ marginTop: 6, maxHeight: 120 }}>{`spec:\n  ignoreApplicationDifferences:\n    - jsonPointers:\n        - ${path}`}</pre>
      {guard.loadError && <div className="muted-sm">Could not read the ApplicationSet: {guard.loadError}</div>}
    </div>
  )
}

export function useGuard(appKey: string, enabled = true) {
  const [g, setG] = useState<store.AppSetGuard | null>(null)
  useEffect(() => {
    if (!enabled) return
    API.AppSetGuard(appKey).then(setG).catch(() => setG(null))
  }, [appKey, enabled])
  return g
}

// ---- sync policy -----------------------------------------------------------------

export function SyncPolicyDialog({
  keys, initial, generatedCount, guard, onClose, onApply,
}: {
  keys: string[]
  initial: { automated: boolean; prune: boolean; selfHeal: boolean }
  generatedCount: number
  guard?: store.AppSetGuard | null
  onClose: () => void
  onApply: (p: store.SyncPolicy) => void
}) {
  const [p, setP] = useState(initial)
  return (
    <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal">
        <header>Sync policy — {keys.length} {keys.length === 1 ? 'application' : 'applications'}</header>
        <div className="content">
          <label className="check"><input type="checkbox" checked={p.automated} onChange={(e) => setP({ ...p, automated: e.target.checked })} /> <b>Automated sync</b> — sync whenever Git changes</label>
          <label className="check" style={{ marginLeft: 22, opacity: p.automated ? 1 : 0.5 }}>
            <input type="checkbox" disabled={!p.automated} checked={p.prune} onChange={(e) => setP({ ...p, prune: e.target.checked })} /> Prune — delete resources removed from Git
          </label>
          <label className="check" style={{ marginLeft: 22, opacity: p.automated ? 1 : 0.5 }}>
            <input type="checkbox" disabled={!p.automated} checked={p.selfHeal} onChange={(e) => setP({ ...p, selfHeal: e.target.checked })} /> Self-heal — undo manual changes in the cluster
          </label>
          {keys.length === 1 && guard !== undefined ? (
            <GuardBanner guard={guard} path="/spec/syncPolicy" what="the sync policy" />
          ) : generatedCount > 0 ? (
            <div className="alert" style={{ background: 'var(--warning-bg)', color: 'var(--warning-fg)' }}>
              {generatedCount} of the selected apps are generated by ApplicationSets. Unless those ApplicationSets ignore
              <code> /spec/syncPolicy</code> (ignoreApplicationDifferences), the change will be reverted.
            </div>
          ) : null}
        </div>
        <footer>
          <button className="btn" onClick={onClose}>Cancel</button>
          <button className="btn primary" onClick={() => onApply(store.SyncPolicy.createFrom(p))}>Apply</button>
        </footer>
      </div>
    </div>
  )
}

// ---- parameters ------------------------------------------------------------------

type Src = Record<string, any> // eslint-disable-line @typescript-eslint/no-explicit-any
type Param = { name: string; value: string; forceString?: boolean }

export function ParametersView({ appKey, notify }: { appKey: string; notify: (m: string, ok: boolean) => void }) {
  const [data, setData] = useState<store.AppSources | null>(null)
  const [err, setErr] = useState('')
  const [rev, setRev] = useState(0)
  const guard = useGuard(appKey)

  useEffect(() => {
    API.AppSources(appKey).then(setData).catch((e) => setErr(String(e)))
  }, [appKey, rev])

  if (err) return <div className="alert">{err}</div>
  if (!data) return <div className="help">Loading parameters…</div>
  if (!data.sources?.length) return <div className="help">This application has no source.</div>
  return (
    <>
      <div className="help" style={{ marginBottom: 10 }}>
        Overrides are stored in the Application spec in Argo CD, not in Git. After saving, sync the app to apply them.
      </div>
      {data.sources.map((s, i) => (
        <SourceEditor
          key={i + ':' + rev}
          index={i}
          multi={data.multi}
          source={s}
          guard={guard}
          onSave={async (next) => {
            await API.SaveSource(appKey, i, next)
            notify('Parameters saved — sync the app to apply them', true)
            setRev((r) => r + 1)
          }}
        />
      ))}
    </>
  )
}

function SourceEditor({ index, multi, source, guard, onSave }: { index: number; multi: boolean; source: Src; guard: store.AppSetGuard | null; onSave: (s: Src) => Promise<void> }) {
  const [rev, setRev] = useState<string>(source.targetRevision ?? '')
  const [helmOn, setHelmOn] = useState<boolean>(!!source.helm || !!source.chart)
  const [kustOn, setKustOn] = useState<boolean>(!!source.kustomize)
  const helm = source.helm ?? {}
  const kust = source.kustomize ?? {}
  const [release, setRelease] = useState<string>(helm.releaseName ?? '')
  const [valueFiles, setValueFiles] = useState<string>((helm.valueFiles ?? []).join('\n'))
  const [values, setValues] = useState<string>(helm.values ?? (helm.valuesObject ? JSON.stringify(helm.valuesObject, null, 2) : ''))
  const [params, setParams] = useState<Param[]>(helm.parameters ?? [])
  const [images, setImages] = useState<string>((kust.images ?? []).join('\n'))
  const [prefix, setPrefix] = useState<string>(kust.namePrefix ?? '')
  const [suffix, setSuffix] = useState<string>(kust.nameSuffix ?? '')
  const [busy, setBusy] = useState(false)
  const [err, setErr] = useState('')
  const path = multi ? `/spec/sources/${index}` : '/spec/source'

  const build = (): Src => {
    const next: Src = { ...source, targetRevision: rev || undefined }
    if (helmOn) {
      const h: Src = { ...helm }
      h.releaseName = release || undefined
      const vf = valueFiles.split('\n').map((x) => x.trim()).filter(Boolean)
      h.valueFiles = vf.length ? vf : undefined
      if (helm.valuesObject && values === JSON.stringify(helm.valuesObject, null, 2)) {
        // untouched valuesObject: keep as is
      } else {
        delete h.valuesObject
        h.values = values.trim() ? values : undefined
      }
      const ps = params.filter((p) => p.name.trim())
      h.parameters = ps.length ? ps : undefined
      next.helm = h
    }
    if (kustOn) {
      const imgs = images.split('\n').map((x) => x.trim()).filter(Boolean)
      next.kustomize = { ...kust, images: imgs.length ? imgs : undefined, namePrefix: prefix || undefined, nameSuffix: suffix || undefined }
    }
    return JSON.parse(JSON.stringify(next)) // drop undefined
  }

  const save = async () => {
    setBusy(true)
    setErr('')
    try {
      await onSave(build())
    } catch (e) {
      setErr(String(e))
    }
    setBusy(false)
  }

  return (
    <div className="card" style={{ padding: 16, marginBottom: 14 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
        <b>{multi ? `Source ${index + 1}` : 'Source'}</b>
        <span className="mono muted-sm">{source.repoURL}{source.chart ? ` · chart ${source.chart}` : source.path ? ` · ${source.path}` : ''}{source.ref ? ` · ref ${source.ref}` : ''}</span>
      </div>
      <GuardBanner guard={guard} path={path} what="these parameters" />
      <div className="row2col">
        <div className="field">
          <label>{source.chart ? 'Chart version' : 'Target revision (branch, tag or commit)'}</label>
          <input type="text" className="mono" value={rev} onChange={(e) => setRev(e.target.value)} placeholder="HEAD" />
        </div>
      </div>

      {helmOn ? (
        <div className="param-section">
          <h4>Helm</h4>
          <div className="row2col">
            <div className="field"><label>Release name</label><input type="text" value={release} onChange={(e) => setRelease(e.target.value)} /></div>
            <div className="field"><label>Value files (one per line)</label><textarea rows={2} className="mono" value={valueFiles} onChange={(e) => setValueFiles(e.target.value)} /></div>
          </div>
          <div className="field">
            <label>Values (YAML) {helm.valuesObject ? '— shown from valuesObject' : ''}</label>
            <textarea rows={10} className="mono code-block" value={values} spellCheck={false} onChange={(e) => setValues(e.target.value)} />
          </div>
          <div className="field">
            <label>Parameters (--set)</label>
            <table className="mini-table">
              <tbody>
                {params.map((p, i) => (
                  <tr key={i}>
                    <td><input type="text" className="mono inline-input" value={p.name} placeholder="image.tag" onChange={(e) => setParams(params.map((x, j) => (j === i ? { ...x, name: e.target.value } : x)))} /></td>
                    <td><input type="text" className="mono inline-input" value={p.value} onChange={(e) => setParams(params.map((x, j) => (j === i ? { ...x, value: e.target.value } : x)))} /></td>
                    <td style={{ whiteSpace: 'nowrap' }}>
                      <label className="check" title="--set-string"><input type="checkbox" checked={!!p.forceString} onChange={(e) => setParams(params.map((x, j) => (j === i ? { ...x, forceString: e.target.checked } : x)))} /> string</label>
                    </td>
                    <td><button className="btn sm ghost" onClick={() => setParams(params.filter((_, j) => j !== i))}>✕</button></td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div><button className="btn sm" onClick={() => setParams([...params, { name: '', value: '' }])}>＋ Parameter</button></div>
          </div>
        </div>
      ) : null}

      {kustOn ? (
        <div className="param-section">
          <h4>Kustomize</h4>
          <div className="field">
            <label>Images (one per line, e.g. <code>ghcr.io/acme/app:v2.4.0</code> or <code>app=ghcr.io/acme/app:v2.4.0</code>)</label>
            <textarea rows={3} className="mono" value={images} onChange={(e) => setImages(e.target.value)} />
          </div>
          <div className="row2col">
            <div className="field"><label>Name prefix</label><input type="text" value={prefix} onChange={(e) => setPrefix(e.target.value)} /></div>
            <div className="field"><label>Name suffix</label><input type="text" value={suffix} onChange={(e) => setSuffix(e.target.value)} /></div>
          </div>
        </div>
      ) : null}

      {!helmOn || !kustOn ? (
        <div style={{ display: 'flex', gap: 6, marginTop: 10 }}>
          {!helmOn && !kustOn && <span className="muted-sm" style={{ alignSelf: 'center' }}>Plain manifests. Add overrides:</span>}
          {!helmOn && !kustOn && <button className="btn sm" onClick={() => setHelmOn(true)}>＋ Helm</button>}
          {!kustOn && !helmOn && <button className="btn sm" onClick={() => setKustOn(true)}>＋ Kustomize</button>}
        </div>
      ) : null}

      {err && <div className="alert" style={{ marginTop: 10 }}>{err}</div>}
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 12 }}>
        <button className="btn primary" disabled={busy} onClick={save}>{busy ? 'Saving…' : 'Save parameters'}</button>
      </div>
    </div>
  )
}
