// mockargo is a fake Argo CD API server for developing and testing Syncscope
// without a real cluster. It serves thousands of apps generated by
// ApplicationSets, a watch stream with live changes, resource actions, local
// login (admin/admin) and a tiny OIDC provider so the SSO flow can be exercised.
//
//	go run ./cmd/mockargo -port 8099 -apps 15000
package main

import (
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"net/http"

	"github.com/gorilla/websocket"
	"strconv"
	"strings"
	"sync"
	"time"
)

var (
	port    = flag.Int("port", 8099, "listen port")
	nApps   = flag.Int("apps", 15000, "number of applications")
	label   = flag.String("name", "mock", "instance label used in names")
	tokenMu sync.Mutex
	tokens  = map[string]string{} // token -> user
)

type obj = map[string]any

type app struct {
	Name, AppSet, Project, Cluster, NS, Repo, Path string
	Sync, Health, Phase, OpMsg                     string
	Retry                                          int
	Conditions                                     []obj
	FailedRes                                      []obj
	Degraded                                       []obj
	RV                                             int
	Reconciled                                     time.Time
	Finished                                       time.Time
	// spec state editable through the API
	Manual     bool // auto-sync disabled
	NoPrune    bool
	NoSelfHeal bool
	Spec       obj // full spec once edited via PUT
	Annots     map[string]any
}

func (a *app) spec(cs string) obj {
	if a.Spec != nil {
		return a.Spec
	}
	var src obj
	switch {
	case strings.HasPrefix(a.Name, "platform-addons"):
		src = obj{"repoURL": "https://charts.bitnami.com/bitnami", "chart": "redis", "targetRevision": "19.6.1",
			"helm": obj{"releaseName": a.Name, "valueFiles": []string{"values-prod.yaml"},
				"values":     "architecture: standalone\nauth:\n  enabled: true\nmaster:\n  resources:\n    limits:\n      memory: 512Mi\n",
				"parameters": []obj{{"name": "replica.replicaCount", "value": "2"}, {"name": "image.tag", "value": "7.2.5"}}}}
	case strings.Contains(a.Name, "-api-"):
		src = obj{"repoURL": a.Repo, "path": a.Path, "targetRevision": "main",
			"kustomize": obj{"images": []string{"ghcr.io/acme/app:v2.3.1"}, "namePrefix": ""}}
	default:
		src = obj{"repoURL": a.Repo, "path": a.Path, "targetRevision": "main"}
	}
	sp := obj{}
	if !a.Manual {
		sp["automated"] = obj{"prune": !a.NoPrune, "selfHeal": !a.NoSelfHeal}
	}
	return obj{"project": a.Project, "source": src, "destination": obj{"server": cs, "namespace": a.NS}, "syncPolicy": sp}
}

var (
	mu   sync.RWMutex
	apps = map[string]*app{}
	rv   = 1000
	subs = map[chan obj]struct{}{}
)

var clusters = []obj{
	{"server": "https://kubernetes.default.svc", "name": "in-cluster"},
	{"server": "https://prod-eu-1.k8s.example.com", "name": "prod-eu-1"},
	{"server": "https://prod-us-1.k8s.example.com", "name": "prod-us-1"},
	{"server": "https://staging.k8s.example.com", "name": "staging"},
	{"server": "https://dev.k8s.example.com", "name": "dev"},
	{"server": "https://legacy.k8s.example.com", "name": "legacy-dc"},
}

var appsets = []string{"payments", "checkout", "identity", "search", "notifications", "reporting", "billing", "platform-addons", "observability", "data-pipeline"}

func gen() {
	r := rand.New(rand.NewSource(42))
	services := []string{"api", "worker", "web", "cron", "gateway", "consumer", "scheduler", "admin", "sync", "export"}
	for i := 0; i < *nApps; i++ {
		as := appsets[i%len(appsets)]
		cl := clusters[r.Intn(len(clusters))]["name"].(string)
		svc := services[r.Intn(len(services))]
		name := fmt.Sprintf("%s-%s-%s-%04d", as, svc, cl, i)
		a := &app{Name: name, AppSet: as, Project: strings.Split(as, "-")[0], Cluster: cl, NS: as + "-" + svc,
			Repo: "https://github.com/acme/deploy.git", Path: "apps/" + as + "/" + svc, Sync: "Synced", Health: "Healthy",
			Phase: "Succeeded", OpMsg: "successfully synced (all tasks run)", RV: rv, Reconciled: time.Now(), Finished: time.Now().Add(-time.Duration(r.Intn(72*60)) * time.Minute)}
		if i%10 == 7 {
			a.AppSet = ""
		}
		switch x := r.Intn(1000); {
		case x < 12:
			a.Phase, a.Sync, a.OpMsg = "Failed", "OutOfSync", "one or more objects failed to apply, reason: Deployment.apps \""+svc+"\" is invalid: spec.template.spec.containers[0].image: Required value"
			a.FailedRes = []obj{{"group": "apps", "version": "v1", "kind": "Deployment", "namespace": a.NS, "name": svc, "status": "SyncFailed",
				"message": "Deployment.apps \"" + svc + "\" is invalid: spec.template.spec.containers[0].image: Required value"}}
		case x < 22:
			a.Health = "Degraded"
			a.Degraded = []obj{{"kind": "Pod", "name": svc + "-7d9f8b6c5d-x2k9p", "msg": "back-off 5m0s restarting failed container=app", "reason": "CrashLoopBackOff"}}
		case x < 27:
			a.Health = "Degraded"
			a.Degraded = []obj{{"kind": "Pod", "name": svc + "-5c6d7e8f9a-q8w7e", "msg": "Back-off pulling image \"ghcr.io/acme/" + svc + ":v2.3.1\"", "reason": "ImagePullBackOff"}}
		case x < 33:
			a.Sync, a.Health = "Unknown", "Unknown"
			a.Conditions = []obj{{"type": "ComparisonError", "message": "Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = authentication required: Repository not found."}}
		case x < 36:
			a.Phase, a.Retry, a.OpMsg = "Running", 3, "Retrying attempt #3 at 10:41AM: waiting for healthy state of apps/Deployment/"+svc
		case x < 80:
			a.Sync = "OutOfSync"
		case x < 90:
			a.Health = "Progressing"
		case x < 95:
			a.Conditions = []obj{{"type": "OrphanedResourceWarning", "message": "Application has 2 orphaned resources"}}
		}
		apps[name] = a
	}
}

func (a *app) toJSON() obj {
	cs := ""
	for _, c := range clusters {
		if c["name"] == a.Cluster {
			cs = c["server"].(string)
		}
	}
	meta := obj{"name": a.Name, "namespace": "argocd", "resourceVersion": fmt.Sprint(a.RV), "annotations": a.Annots,
		"labels": obj{"team": a.Project, "env": a.Cluster}, "creationTimestamp": "2025-01-10T10:00:00Z"}
	if a.AppSet != "" {
		meta["ownerReferences"] = []obj{{"apiVersion": "argoproj.io/v1alpha1", "kind": "ApplicationSet", "name": a.AppSet}}
	}
	res := []obj{
		{"group": "apps", "version": "v1", "kind": "Deployment", "namespace": a.NS, "name": "app", "status": a.Sync},
		{"version": "v1", "kind": "Service", "namespace": a.NS, "name": "app", "status": "Synced"},
		{"version": "v1", "kind": "ConfigMap", "namespace": a.NS, "name": "app-config", "status": a.Sync},
		{"group": "networking.k8s.io", "version": "v1", "kind": "Ingress", "namespace": a.NS, "name": "app", "status": "Synced"},
	}
	op := obj{"phase": a.Phase, "message": a.OpMsg, "startedAt": a.Finished.Add(-30 * time.Second).Format(time.RFC3339), "retryCount": a.Retry}
	if a.Phase != "Running" {
		op["finishedAt"] = a.Finished.Format(time.RFC3339)
	}
	if len(a.FailedRes) > 0 {
		op["syncResult"] = obj{"revision": "9f8e7d6c5b4a39281706f5e4d3c2b1a098765432", "resources": a.FailedRes}
	}
	return obj{
		"metadata": meta,
		"spec":     a.spec(cs),
		"status": obj{
			"sync":           obj{"status": a.Sync, "revision": "9f8e7d6c5b4a39281706f5e4d3c2b1a098765432"},
			"health":         obj{"status": a.Health},
			"operationState": op, "conditions": a.Conditions, "resources": res,
			"reconciledAt": a.Reconciled.Format(time.RFC3339),
			"history": []obj{{"id": 1, "revision": "1a2b3c4d5e6f", "deployedAt": a.Finished.Add(-48 * time.Hour).Format(time.RFC3339)},
				{"id": 2, "revision": "9f8e7d6c5b4a", "deployedAt": a.Finished.Format(time.RFC3339)}},
		},
	}
}

func publish(a *app, typ string) {
	mu.Lock()
	rv++
	a.RV = rv
	a.Reconciled = time.Now()
	ev := obj{"result": obj{"type": typ, "application": a.toJSON()}}
	for ch := range subs {
		select {
		case ch <- ev:
		default:
		}
	}
	mu.Unlock()
}

// churn simulates a busy control plane.
func churn() {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	for range time.Tick(400 * time.Millisecond) {
		mu.RLock()
		var pick *app
		n := r.Intn(len(apps))
		for _, a := range apps {
			if n == 0 {
				pick = a
				break
			}
			n--
		}
		mu.RUnlock()
		if pick == nil {
			continue
		}
		mu.Lock()
		switch r.Intn(4) {
		case 0:
			if pick.Health == "Healthy" {
				pick.Health = "Progressing"
			} else if pick.Health == "Progressing" {
				pick.Health = "Healthy"
			}
		case 1:
			if pick.Sync == "Synced" && pick.Phase == "Succeeded" {
				pick.Sync = "OutOfSync"
			}
		default:
			pick.Finished = time.Now()
		}
		mu.Unlock()
		publish(pick, "MODIFIED")
	}
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}

func authed(r *http.Request) bool {
	tok := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
	if c, err := r.Cookie("argocd.token"); tok == "" && err == nil {
		tok = c.Value
	}
	tokenMu.Lock()
	defer tokenMu.Unlock()
	_, ok := tokens[tok]
	return ok
}

func issue(user string, ttl time.Duration) string {
	hdr := base64.RawURLEncoding.EncodeToString([]byte(`{"alg":"none"}`))
	body, _ := json.Marshal(obj{"sub": user, "exp": time.Now().Add(ttl).Unix(), "iat": time.Now().Unix(), "n": rand.Int()})
	tok := hdr + "." + base64.RawURLEncoding.EncodeToString(body) + ".sig"
	tokenMu.Lock()
	tokens[tok] = user
	tokenMu.Unlock()
	return tok
}

func main() {
	flag.Parse()
	gen()
	go churn()
	base := fmt.Sprintf("http://localhost:%d", *port)
	mux := http.NewServeMux()

	mux.HandleFunc("/api/version", func(w http.ResponseWriter, r *http.Request) { writeJSON(w, obj{"Version": "v3.1.0+mock"}) })
	mux.HandleFunc("/api/v1/settings", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, obj{"url": base, "dexConfig": obj{"connectors": []obj{{"name": "Mock SSO (" + *label + ")", "type": "oidc"}}}})
	})
	// --- fake Dex ---
	mux.HandleFunc("/api/dex/.well-known/openid-configuration", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, obj{"issuer": base + "/api/dex", "authorization_endpoint": base + "/api/dex/auth", "token_endpoint": base + "/api/dex/token",
			"code_challenge_methods_supported": []string{"S256"}})
	})
	mux.HandleFunc("/api/dex/auth", func(w http.ResponseWriter, r *http.Request) {
		q := r.URL.Query()
		fmt.Fprintf(w, `<html><body style="font-family:sans-serif;padding:40px"><h2>Mock SSO — %s</h2>
<p>client_id=%s</p><a href="%s?code=mockcode&state=%s" style="font-size:18px">Sign in as dev@acme.io →</a></body></html>`,
			*label, q.Get("client_id"), q.Get("redirect_uri"), q.Get("state"))
	})
	mux.HandleFunc("/api/dex/token", func(w http.ResponseWriter, r *http.Request) {
		_ = r.ParseForm()
		if r.Form.Get("grant_type") == "authorization_code" && r.Form.Get("code_verifier") == "" {
			w.WriteHeader(400)
			writeJSON(w, obj{"error": "invalid_request", "error_description": "missing code_verifier"})
			return
		}
		writeJSON(w, obj{"id_token": issue("dev@acme.io", 2*time.Minute), "refresh_token": "mock-refresh", "token_type": "bearer"})
	})
	// --- auth ---
	mux.HandleFunc("/api/v1/session", func(w http.ResponseWriter, r *http.Request) {
		var b struct{ Username, Password string }
		_ = json.NewDecoder(r.Body).Decode(&b)
		if b.Username != "admin" || b.Password != "admin" {
			w.WriteHeader(401)
			writeJSON(w, obj{"error": "Invalid username or password", "message": "Invalid username or password"})
			return
		}
		writeJSON(w, obj{"token": issue("admin", time.Hour)})
	})
	mux.HandleFunc("/api/v1/session/userinfo", func(w http.ResponseWriter, r *http.Request) {
		if !authed(r) {
			writeJSON(w, obj{"loggedIn": false})
			return
		}
		tokenMu.Lock()
		u := tokens[strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")]
		tokenMu.Unlock()
		writeJSON(w, obj{"loggedIn": true, "username": u})
	})

	guard := func(h http.HandlerFunc) http.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) {
			if !authed(r) {
				w.WriteHeader(401)
				writeJSON(w, obj{"error": "invalid session", "message": "invalid session: token has invalid claims: token is expired"})
				return
			}
			h(w, r)
		}
	}

	mux.HandleFunc("/api/v1/applications", guard(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			var in obj
			_ = json.NewDecoder(r.Body).Decode(&in)
			md, _ := in["metadata"].(map[string]any)
			spec, _ := in["spec"].(map[string]any)
			name, _ := md["name"].(string)
			if name == "" || spec == nil {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "application spec is invalid: metadata.name and spec are required"})
				return
			}
			mu.Lock()
			if _, exists := apps[name]; exists && r.URL.Query().Get("upsert") != "true" {
				mu.Unlock()
				w.WriteHeader(409)
				writeJSON(w, obj{"message": "existing application spec is different, use upsert flag to force update"})
				return
			}
			proj, _ := spec["project"].(string)
			a := &app{Name: name, Project: proj, Cluster: "in-cluster", NS: name, Repo: "https://github.com/acme/deploy.git", Path: "apps/" + name,
				Sync: "OutOfSync", Health: "Missing", Phase: "Succeeded", OpMsg: "", Reconciled: time.Now(), Finished: time.Now(), Spec: spec}
			apps[name] = a
			mu.Unlock()
			publish(a, "ADDED")
			writeJSON(w, a.toJSON())
			return
		}
		mu.RLock()
		items := make([]obj, 0, len(apps))
		for _, a := range apps {
			items = append(items, a.toJSON())
		}
		v := rv
		mu.RUnlock()
		writeJSON(w, obj{"metadata": obj{"resourceVersion": fmt.Sprint(v)}, "items": items})
	}))
	mux.HandleFunc("/api/v1/stream/applications", guard(func(w http.ResponseWriter, r *http.Request) {
		fl, _ := w.(http.Flusher)
		ch := make(chan obj, 256)
		mu.Lock()
		subs[ch] = struct{}{}
		mu.Unlock()
		defer func() { mu.Lock(); delete(subs, ch); mu.Unlock() }()
		w.Header().Set("Content-Type", "application/json")
		fl.Flush()
		enc := json.NewEncoder(w)
		for {
			select {
			case <-r.Context().Done():
				return
			case ev := <-ch:
				_ = enc.Encode(ev)
				fl.Flush()
			}
		}
	}))
	mux.HandleFunc("/api/v1/applications/", guard(func(w http.ResponseWriter, r *http.Request) {
		parts := strings.Split(strings.TrimPrefix(r.URL.Path, "/api/v1/applications/"), "/")
		mu.RLock()
		a := apps[parts[0]]
		mu.RUnlock()
		if a == nil {
			w.WriteHeader(404)
			writeJSON(w, obj{"message": "application not found"})
			return
		}
		sub := strings.Join(parts[1:], "/")
		switch {
		case sub == "" && r.Method == http.MethodGet:
			if r.URL.Query().Get("refresh") != "" {
				go publish(a, "MODIFIED")
			}
			mu.RLock()
			j := a.toJSON()
			mu.RUnlock()
			writeJSON(w, j)
		case sub == "sync":
			if a.Conditions != nil && a.Conditions[0]["type"] == "ComparisonError" {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "error resolving repo revision: authentication required: Repository not found."})
				return
			}
			mu.Lock()
			a.Phase, a.OpMsg, a.Retry = "Running", "syncing", 0
			mu.Unlock()
			publish(a, "MODIFIED")
			go func() {
				time.Sleep(2 * time.Second)
				mu.Lock()
				if a.FailedRes == nil {
					a.Phase, a.Sync, a.OpMsg, a.Finished = "Succeeded", "Synced", "successfully synced (all tasks run)", time.Now()
				} else {
					a.Phase, a.OpMsg, a.Finished = "Failed", "one or more objects failed to apply", time.Now()
				}
				mu.Unlock()
				publish(a, "MODIFIED")
			}()
			writeJSON(w, a.toJSON())
		case sub == "operation" && r.Method == http.MethodDelete:
			mu.Lock()
			a.Phase, a.OpMsg, a.Finished = "Failed", "Operation terminated", time.Now()
			mu.Unlock()
			publish(a, "MODIFIED")
			writeJSON(w, obj{})
		case sub == "resource/actions/v2":
			var b map[string]any
			_ = json.NewDecoder(r.Body).Decode(&b)
			if act := b["action"]; act != "restart" && act != "pause" && act != "resume" {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "unknown action"})
				return
			}
			if a.Cluster == "legacy-dc" {
				w.WriteHeader(500)
				writeJSON(w, obj{"message": "failed to patch Deployment " + a.NS + "/app: the server has asked for the client to provide credentials"})
				return
			}
			writeJSON(w, obj{})
		case sub == "resource-tree":
			// Deployment -> ReplicaSet -> Pods, Service -> EndpointSlice, ConfigMap.
			ns := a.NS
			depH := a.Health
			if depH == "Unknown" {
				depH = "Healthy"
			}
			nodes := []obj{
				{"group": "apps", "version": "v1", "kind": "Deployment", "namespace": ns, "name": "app", "uid": "dep", "health": obj{"status": depH},
					"info": []obj{{"name": "Revision", "value": "Rev:4"}}, "images": []string{"ghcr.io/acme/app:v2.3.1"}},
				{"group": "apps", "version": "v1", "kind": "ReplicaSet", "namespace": ns, "name": "app-7d9f8b6c5d", "uid": "rs",
					"parentRefs": []obj{{"group": "apps", "kind": "Deployment", "namespace": ns, "name": "app", "uid": "dep"}},
					"health":     obj{"status": depH}, "info": []obj{{"name": "Revision", "value": "Rev:4"}}},
				{"group": "apps", "version": "v1", "kind": "ReplicaSet", "namespace": ns, "name": "app-5c6d7e8f9a", "uid": "rs-old",
					"parentRefs": []obj{{"group": "apps", "kind": "Deployment", "namespace": ns, "name": "app", "uid": "dep"}},
					"health":     obj{"status": "Healthy"}, "info": []obj{{"name": "Revision", "value": "Rev:3"}}},
				{"version": "v1", "kind": "Service", "namespace": ns, "name": "app", "uid": "svc", "health": obj{"status": "Healthy"}},
				{"group": "discovery.k8s.io", "version": "v1", "kind": "EndpointSlice", "namespace": ns, "name": "app-x7k2p", "uid": "eps",
					"parentRefs": []obj{{"kind": "Service", "namespace": ns, "name": "app", "uid": "svc"}}},
				{"version": "v1", "kind": "ConfigMap", "namespace": ns, "name": "app-config", "uid": "cm"},
				{"group": "networking.k8s.io", "version": "v1", "kind": "Ingress", "namespace": ns, "name": "app", "uid": "ing", "health": obj{"status": "Healthy"}},
			}
			for i, d := range a.Degraded {
				nodes = append(nodes, obj{"version": "v1", "kind": d["kind"], "namespace": ns, "name": d["name"], "uid": fmt.Sprint("bad", i),
					"parentRefs": []obj{{"group": "apps", "kind": "ReplicaSet", "namespace": ns, "name": "app-7d9f8b6c5d", "uid": "rs"}},
					"health":     obj{"status": "Degraded", "message": d["msg"]}, "info": []obj{{"name": "Status Reason", "value": d["reason"]}, {"name": "Containers", "value": "0/1"}, {"name": "Restart Count", "value": "17"}}})
			}
			for i := 0; i < 2; i++ {
				nodes = append(nodes, obj{"version": "v1", "kind": "Pod", "namespace": ns, "name": fmt.Sprintf("app-7d9f8b6c5d-ab1%dc", i), "uid": fmt.Sprint("pod", i),
					"parentRefs": []obj{{"group": "apps", "kind": "ReplicaSet", "namespace": ns, "name": "app-7d9f8b6c5d", "uid": "rs"}},
					"health":     obj{"status": "Healthy"}, "images": []string{"ghcr.io/acme/app:v2.3.1"},
					"info": []obj{{"name": "Status Reason", "value": "Running"}, {"name": "Containers", "value": "1/1"}, {"name": "Node", "value": "gke-pool-1-a1b2"}}})
			}
			writeJSON(w, obj{"nodes": nodes})
		case sub == "" && r.Method == http.MethodPatch:
			var b struct{ Patch string }
			_ = json.NewDecoder(r.Body).Decode(&b)
			var p struct {
				Metadata struct {
					Annotations map[string]any `json:"annotations"`
				} `json:"metadata"`
				Spec struct {
					SyncPolicy map[string]json.RawMessage `json:"syncPolicy"`
				} `json:"spec"`
			}
			_ = json.Unmarshal([]byte(b.Patch), &p)
			mu.Lock()
			for k, v := range p.Metadata.Annotations {
				if a.Annots == nil {
					a.Annots = map[string]any{}
				}
				if v == nil {
					delete(a.Annots, k)
				} else {
					a.Annots[k] = v
				}
			}
			if raw, ok := p.Spec.SyncPolicy["automated"]; ok {
				if string(raw) == "null" {
					a.Manual = true
				} else {
					var au struct{ Prune, SelfHeal bool }
					_ = json.Unmarshal(raw, &au)
					a.Manual, a.NoPrune, a.NoSelfHeal = false, !au.Prune, !au.SelfHeal
				}
				a.Spec = nil
			}
			mu.Unlock()
			publish(a, "MODIFIED")
			writeJSON(w, a.toJSON())
		case sub == "" && r.Method == http.MethodPut:
			var full obj
			_ = json.NewDecoder(r.Body).Decode(&full)
			spec, _ := full["spec"].(map[string]any)
			if spec == nil {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "spec is required"})
				return
			}
			if src, ok := spec["source"].(map[string]any); ok {
				if rev, _ := src["targetRevision"].(string); rev == "does-not-exist" {
					w.WriteHeader(400)
					writeJSON(w, obj{"message": "application spec for " + a.Name + " is invalid: InvalidSpecError: Unable to resolve 'does-not-exist' to a commit SHA"})
					return
				}
			}
			mu.Lock()
			a.Spec = spec
			mu.Unlock()
			publish(a, "MODIFIED")
			writeJSON(w, a.toJSON())
		case sub == "syncwindows":
			win := obj{"kind": "deny", "schedule": "0 22 * * *", "duration": "8h", "applications": []string{"*"}, "manualSync": true, "timeZone": "Europe/Zurich"}
			out := obj{"assignedWindows": []obj{win}, "activeWindows": []obj{}, "canSync": true}
			if a.Project == "billing" {
				out["activeWindows"], out["canSync"] = []obj{win}, false
			}
			writeJSON(w, out)
		case sub == "managed-resources":
			img := "ghcr.io/acme/app:v2.3.1"
			liveImg := img
			replicas := 2
			if a.Sync == "OutOfSync" {
				liveImg = "ghcr.io/acme/app:v2.2.0"
			}
			dep := func(image string, rep int, live bool) string {
				m := obj{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": obj{"name": "app", "namespace": a.NS, "labels": obj{"app": "app"}},
					"spec": obj{"replicas": rep, "selector": obj{"matchLabels": obj{"app": "app"}},
						"template": obj{"metadata": obj{"labels": obj{"app": "app"}}, "spec": obj{"containers": []obj{{"name": "app", "image": image,
							"resources": obj{"limits": obj{"memory": "512Mi"}}, "ports": []obj{{"containerPort": 8080}}}}}}}}
				if live {
					m["metadata"].(obj)["managedFields"] = []obj{{"manager": "argocd-controller"}}
					m["status"] = obj{"replicas": rep, "readyReplicas": rep}
				}
				b, _ := json.Marshal(m)
				return string(b)
			}
			cm := func(level string) string {
				b, _ := json.Marshal(obj{"apiVersion": "v1", "kind": "ConfigMap", "metadata": obj{"name": "app-config", "namespace": a.NS},
					"data": obj{"LOG_LEVEL": level, "FEATURE_X": "true"}})
				return string(b)
			}
			liveLevel := "info"
			if a.Sync == "OutOfSync" {
				liveLevel = "debug"
			}
			svc, _ := json.Marshal(obj{"apiVersion": "v1", "kind": "Service", "metadata": obj{"name": "app", "namespace": a.NS}, "spec": obj{"ports": []obj{{"port": 80, "targetPort": 8080}}}})
			writeJSON(w, obj{"items": []obj{
				{"group": "apps", "kind": "Deployment", "namespace": a.NS, "name": "app", "liveState": dep(liveImg, replicas, true), "targetState": dep(img, replicas, false),
					"normalizedLiveState": dep(liveImg, replicas, false), "predictedLiveState": dep(img, replicas, false), "modified": liveImg != img},
				{"kind": "ConfigMap", "namespace": a.NS, "name": "app-config", "liveState": cm(liveLevel), "targetState": cm("info"),
					"normalizedLiveState": cm(liveLevel), "predictedLiveState": cm("info"), "modified": liveLevel != "info"},
				{"kind": "Service", "namespace": a.NS, "name": "app", "liveState": string(svc), "targetState": string(svc), "normalizedLiveState": string(svc), "predictedLiveState": string(svc)},
			}})
		case sub == "events":
			q := r.URL.Query()
			now := time.Now()
			ev := func(typ, reason, msg, kind, name string, count int, ago time.Duration) obj {
				return obj{"type": typ, "reason": reason, "message": msg, "count": count,
					"firstTimestamp": now.Add(-ago * 3).Format(time.RFC3339), "lastTimestamp": now.Add(-ago).Format(time.RFC3339),
					"involvedObject": obj{"kind": kind, "name": name, "namespace": a.NS}, "source": obj{"component": "kubelet"}}
			}
			items := []obj{
				ev("Normal", "ScalingReplicaSet", "Scaled up replica set app-7d9f8b6c5d to 2", "Deployment", "app", 1, 40*time.Minute),
				ev("Normal", "Pulled", "Container image \"ghcr.io/acme/app:v2.3.1\" already present on machine", "Pod", "app-7d9f8b6c5d-ab10c", 1, 39*time.Minute),
				ev("Normal", "ResourceUpdated", "Updated sync status: OutOfSync -> Synced", "Application", a.Name, 3, 20*time.Minute),
			}
			if len(a.Degraded) > 0 {
				pod := a.Degraded[0]["name"].(string)
				items = append(items,
					ev("Warning", "BackOff", "Back-off restarting failed container app in pod "+pod, "Pod", pod, 17, 2*time.Minute),
					ev("Warning", "Unhealthy", "Readiness probe failed: HTTP probe failed with statuscode: 503", "Pod", pod, 42, time.Minute))
			}
			if rn := q.Get("resourceName"); rn != "" {
				var f []obj
				for _, e := range items {
					if e["involvedObject"].(obj)["name"] == rn {
						f = append(f, e)
					}
				}
				items = f
			}
			writeJSON(w, obj{"items": items})
		case sub == "resource/actions" && r.Method == http.MethodGet:
			acts := []obj{}
			switch r.URL.Query().Get("kind") {
			case "Deployment":
				acts = []obj{{"name": "restart", "disabled": false}, {"name": "pause", "disabled": false}, {"name": "resume", "disabled": true}}
			case "StatefulSet", "DaemonSet":
				acts = []obj{{"name": "restart", "disabled": false}}
			}
			writeJSON(w, obj{"actions": acts})
		case sub == "resource" && r.Method == http.MethodDelete:
			writeJSON(w, obj{})
		case sub == "resource" && r.Method == http.MethodPost:
			writeJSON(w, obj{"manifest": "{}"})
		case sub == "" && r.Method == http.MethodDelete:
			mu.Lock()
			delete(apps, a.Name)
			rv++
			ev := obj{"result": obj{"type": "DELETED", "application": a.toJSON()}}
			for ch := range subs {
				select {
				case ch <- ev:
				default:
				}
			}
			mu.Unlock()
			writeJSON(w, obj{})
		case sub == "rollback":
			var b map[string]any
			_ = json.NewDecoder(r.Body).Decode(&b)
			writeJSON(w, a.toJSON())
		case strings.HasPrefix(sub, "revisions/") && strings.HasSuffix(sub, "/metadata"):
			rev := strings.TrimSuffix(strings.TrimPrefix(sub, "revisions/"), "/metadata")
			msgs := map[string]string{"1a2b3c4d5e6f": "feat(" + a.AppSet + "): bump image to v2.3.0", "9f8e7d6c5b4a": "fix: increase memory limit to 512Mi\n\nThe pod was OOMKilled under load."}
			m := msgs[rev]
			if m == "" {
				m = "chore: update manifests"
			}
			writeJSON(w, obj{"author": "Jane Doe <jane@acme.io>", "date": a.Finished.Format(time.RFC3339), "message": m, "tags": []string{}})
		case sub == "resource":
			q := r.URL.Query()
			containers := []obj{{"name": "app", "image": "ghcr.io/acme/app:v2.3.1"}, {"name": "istio-proxy", "image": "istio/proxyv2:1.22"}}
			var spec obj
			if q.Get("kind") == "Pod" {
				spec = obj{"containers": containers, "initContainers": []obj{{"name": "migrate"}}}
			} else {
				spec = obj{"template": obj{"spec": obj{"containers": containers}}}
			}
			man, _ := json.Marshal(obj{"apiVersion": "v1", "kind": q.Get("kind"), "metadata": obj{"name": q.Get("resourceName"), "namespace": q.Get("namespace")}, "spec": spec})
			writeJSON(w, obj{"manifest": string(man)})
		case sub == "logs":
			q := r.URL.Query()
			fl, _ := w.(http.Flusher)
			w.Header().Set("Content-Type", "application/json")
			enc := json.NewEncoder(w)
			pod := q.Get("podName")
			if pod == "" {
				pod = q.Get("resourceName") + "-7d9f8b6c5d-ab10c"
			}
			bad := strings.Contains(pod, "x2k9p") || strings.Contains(pod, "q8w7e")
			tail, _ := strconv.Atoi(q.Get("tailLines"))
			if tail == 0 || tail > 300 {
				tail = 300
			}
			line := func(i int, t time.Time) string {
				if bad && i%7 == 6 {
					return fmt.Sprintf(`{"level":"error","ts":"%s","msg":"failed to connect to postgres","error":"dial tcp 10.0.3.4:5432: connect: connection refused","container":"%s"}`, t.Format(time.RFC3339), q.Get("container"))
				}
				return fmt.Sprintf(`{"level":"info","ts":"%s","msg":"GET /api/v1/items 200","latency_ms":%d,"container":"%s"}`, t.Format(time.RFC3339), 3+i%40, q.Get("container"))
			}
			now := time.Now()
			for i := 0; i < tail; i++ {
				t := now.Add(time.Duration(i-tail) * time.Second)
				_ = enc.Encode(obj{"result": obj{"content": line(i, t), "timeStamp": t.Format(time.RFC3339Nano), "podName": pod}})
			}
			if bad {
				_ = enc.Encode(obj{"result": obj{"content": "panic: runtime error: invalid memory address or nil pointer dereference", "timeStamp": now.Format(time.RFC3339Nano), "podName": pod}})
			}
			fl.Flush()
			if q.Get("follow") != "true" {
				_ = enc.Encode(obj{"result": obj{"last": true}})
				return
			}
			for i := tail; ; i++ {
				select {
				case <-r.Context().Done():
					return
				case <-time.After(700 * time.Millisecond):
					_ = enc.Encode(obj{"result": obj{"content": line(i, time.Now()), "timeStamp": time.Now().Format(time.RFC3339Nano), "podName": pod}})
					fl.Flush()
				}
			}
		default:
			w.WriteHeader(404)
			writeJSON(w, obj{"message": "not found: " + sub})
		}
	}))
	mux.HandleFunc("/api/v1/applicationsets", guard(func(w http.ResponseWriter, r *http.Request) {
		items := []obj{}
		for _, s := range appsets {
			st := obj{"conditions": []obj{{"type": "ErrorOccurred", "status": "False", "reason": "ApplicationSetUpToDate", "message": "Successfully generated parameters"}}}
			if s == "reporting" {
				st = obj{"conditions": []obj{{"type": "ErrorOccurred", "status": "True", "reason": "ApplicationGenerationFromParamsError",
					"message": "failed to execute go template {{.path.basename}}: template: :1:7: executing \"\" at <.path.basename>: map has no entry for key \"path\""}}}
			}
			items = append(items, obj{"metadata": obj{"name": s, "namespace": "argocd"}, "status": st})
		}
		writeJSON(w, obj{"items": items})
	}))
	// Fake web terminal speaking the Argo CD protocol: {"operation":"stdin|resize|stdout","data":...}
	up := websocket.Upgrader{CheckOrigin: func(*http.Request) bool { return true }}
	mux.HandleFunc("/terminal", guard(func(w http.ResponseWriter, r *http.Request) {
		q := r.URL.Query()
		if q.Get("container") == "istio-proxy" {
			w.WriteHeader(400)
			writeJSON(w, obj{"message": "no shell found in container istio-proxy (tried bash, sh)"})
			return
		}
		c, err := up.Upgrade(w, r, nil)
		if err != nil {
			return
		}
		defer c.Close()
		out := func(s string) { _ = c.WriteJSON(obj{"operation": "stdout", "data": s}) }
		prompt := q.Get("pod") + ":/app$ "
		out("\x1b[32mConnected to " + q.Get("namespace") + "/" + q.Get("pod") + " (" + q.Get("container") + ")\x1b[0m\r\n" + prompt)
		line := ""
		for {
			var m struct{ Operation, Data string }
			if err := c.ReadJSON(&m); err != nil {
				return
			}
			if m.Operation != "stdin" {
				continue
			}
			for _, ch := range m.Data {
				switch ch {
				case '\r':
					cmd := strings.TrimSpace(line)
					line = ""
					out("\r\n")
					switch {
					case cmd == "":
					case cmd == "exit":
						out("logout\r\n")
						return
					case cmd == "ls":
						out("app  config  healthcheck.sh  migrations\r\n")
					case cmd == "whoami":
						out("app\r\n")
					case cmd == "env":
						out("HOSTNAME=" + q.Get("pod") + "\r\nLOG_LEVEL=info\r\nPORT=8080\r\n")
					default:
						out("sh: " + strings.Fields(cmd)[0] + ": not found\r\n")
					}
					out(prompt)
				case 127, '\b':
					if len(line) > 0 {
						line = line[:len(line)-1]
						out("\b \b")
					}
				default:
					line += string(ch)
					out(string(ch))
				}
			}
		}
	}))
	mux.HandleFunc("/api/v1/applicationsets/", guard(func(w http.ResponseWriter, r *http.Request) {
		name := strings.TrimPrefix(r.URL.Path, "/api/v1/applicationsets/")
		if r.Method == http.MethodDelete {
			writeJSON(w, obj{})
			return
		}
		conds := []obj{{"type": "ResourcesUpToDate", "status": "True", "reason": "ApplicationSetUpToDate", "message": "All applications have been generated successfully"}}
		if name == "reporting" {
			conds = []obj{{"type": "ErrorOccurred", "status": "True", "reason": "ApplicationGenerationFromParamsError", "message": "failed to execute go template {{.path.basename}}: map has no entry for key \"path\""}}
		}
		writeJSON(w, obj{"metadata": obj{"name": name, "namespace": "argocd"}, "spec": obj{
			"goTemplate": true,
			"generators": []obj{{"matrix": obj{"generators": []obj{
				{"clusters": obj{"selector": obj{"matchLabels": obj{"env": "prod"}}}},
				{"git": obj{"repoURL": "https://github.com/acme/deploy.git", "revision": "main", "directories": []obj{{"path": "apps/" + name + "/*"}}}},
			}}}},
			"template": obj{"metadata": obj{"name": name + "-{{.path.basename}}-{{.name}}"}, "spec": obj{"project": name,
				"source":      obj{"repoURL": "https://github.com/acme/deploy.git", "path": "{{.path.path}}", "targetRevision": "main"},
				"destination": obj{"server": "{{.server}}", "namespace": name + "-{{.path.basename}}"}}},
			"syncPolicy": obj{"preserveResourcesOnDeletion": name == "billing"},
		}, "status": obj{"conditions": conds}})
	}))
	mux.HandleFunc("/api/v1/repositories/", guard(func(w http.ResponseWriter, r *http.Request) { writeJSON(w, obj{}) }))
	mux.HandleFunc("/api/v1/projects/", guard(func(w http.ResponseWriter, r *http.Request) {
		name := strings.TrimPrefix(r.URL.Path, "/api/v1/projects/")
		switch r.Method {
		case http.MethodGet:
			writeJSON(w, obj{"metadata": obj{"name": name, "namespace": "argocd", "resourceVersion": "42"}, "spec": obj{"description": "Team " + name,
				"sourceRepos": []string{"https://github.com/acme/*"}, "destinations": []obj{{"server": "*", "namespace": name + "-*"}},
				"syncWindows": []obj{{"kind": "deny", "schedule": "0 22 * * *", "duration": "8h", "applications": []string{"*"}, "manualSync": true}}}})
		case http.MethodPut:
			var b struct{ Project obj }
			_ = json.NewDecoder(r.Body).Decode(&b)
			if b.Project == nil {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "project is required"})
				return
			}
			writeJSON(w, b.Project)
		default:
			writeJSON(w, obj{})
		}
	}))
	mux.HandleFunc("/api/v1/clusters/", guard(func(w http.ResponseWriter, r *http.Request) { writeJSON(w, obj{}) }))
	mux.HandleFunc("/api/v1/account/", guard(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			writeJSON(w, obj{"token": "eyJhbGciOiJIUzI1NiJ9.mock-api-token"})
			return
		}
		writeJSON(w, obj{})
	}))
	mux.HandleFunc("/api/v1/repositories", guard(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			var in map[string]any
			_ = json.NewDecoder(r.Body).Decode(&in)
			if repo, _ := in["repo"].(string); !strings.HasPrefix(repo, "https://") && !strings.HasPrefix(repo, "git@") {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "rpc error: code = InvalidArgument desc = repository URL must start with https:// or git@"})
				return
			}
			writeJSON(w, in)
			return
		}
		writeJSON(w, obj{"items": []obj{
			{"repo": "https://github.com/acme/deploy.git", "type": "git", "project": "", "connectionState": obj{"status": "Successful"}},
			{"repo": "https://charts.bitnami.com/bitnami", "type": "helm", "name": "bitnami", "connectionState": obj{"status": "Successful"}},
			{"repo": "git@github.com:acme/legacy.git", "type": "git", "connectionState": obj{"status": "Failed", "message": "ssh: handshake failed: knownhosts: key is unknown"}},
		}})
	}))
	mux.HandleFunc("/api/v1/projects", guard(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			writeJSON(w, obj{})
			return
		}
		items := []obj{}
		for _, s := range append([]string{"default"}, appsets...) {
			items = append(items, obj{"metadata": obj{"name": s}, "spec": obj{"description": "Team " + s,
				"sourceRepos":  []string{"https://github.com/acme/*"},
				"destinations": []obj{{"server": "*", "namespace": s + "-*"}},
				"roles":        []obj{{"name": "ci", "policies": []string{"p, proj:" + s + ":ci, applications, sync, " + s + "/*, allow"}}}}})
		}
		writeJSON(w, obj{"items": items})
	}))
	mux.HandleFunc("/api/v1/account", guard(func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, obj{"items": []obj{{"name": "admin", "enabled": true, "capabilities": []string{"login"}}, {"name": "ci-bot", "enabled": true, "capabilities": []string{"apiKey"}, "tokens": []obj{{"id": "t1", "issuedAt": 1730000000}}}}})
	}))
	mux.HandleFunc("/api/v1/clusters", guard(func(w http.ResponseWriter, r *http.Request) {
		items := []obj{}
		for _, c := range clusters {
			cs := obj{"status": "Successful"}
			if c["name"] == "legacy-dc" {
				cs = obj{"status": "Failed", "message": "Get \"https://legacy.k8s.example.com/version\": dial tcp 10.20.0.5:443: i/o timeout"}
			}
			items = append(items, obj{"server": c["server"], "name": c["name"], "connectionState": cs, "info": obj{"serverVersion": "1.31"}})
		}
		writeJSON(w, obj{"items": items})
	}))

	log.Printf("mock Argo CD %q on %s with %d apps (login admin/admin or SSO)", *label, base, len(apps))
	log.Fatal(http.ListenAndServe(fmt.Sprintf("127.0.0.1:%d", *port), mux))
}
