// mockargo is a fake Argo CD API server for developing and testing ArgoDeck
// without a real cluster. It serves thousands of apps generated by
// ApplicationSets, a watch stream with live changes, resource actions, local
// login (admin/admin) and a tiny OIDC provider so the SSO flow can be exercised.
//
//	go run ./cmd/mockargo -port 8099 -apps 15000
package main

import (
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"strings"
	"sync"
	"time"
)

var (
	port    = flag.Int("port", 8099, "listen port")
	nApps   = flag.Int("apps", 15000, "number of applications")
	label   = flag.String("name", "mock", "instance label used in names")
	tokenMu sync.Mutex
	tokens  = map[string]string{} // token -> user
)

type obj = map[string]any

type app struct {
	Name, AppSet, Project, Cluster, NS, Repo, Path string
	Sync, Health, Phase, OpMsg                     string
	Retry                                          int
	Conditions                                     []obj
	FailedRes                                      []obj
	Degraded                                       []obj
	RV                                             int
	Reconciled                                     time.Time
	Finished                                       time.Time
}

var (
	mu   sync.RWMutex
	apps = map[string]*app{}
	rv   = 1000
	subs = map[chan obj]struct{}{}
)

var clusters = []obj{
	{"server": "https://kubernetes.default.svc", "name": "in-cluster"},
	{"server": "https://prod-eu-1.k8s.example.com", "name": "prod-eu-1"},
	{"server": "https://prod-us-1.k8s.example.com", "name": "prod-us-1"},
	{"server": "https://staging.k8s.example.com", "name": "staging"},
	{"server": "https://dev.k8s.example.com", "name": "dev"},
	{"server": "https://legacy.k8s.example.com", "name": "legacy-dc"},
}

var appsets = []string{"payments", "checkout", "identity", "search", "notifications", "reporting", "billing", "platform-addons", "observability", "data-pipeline"}

func gen() {
	r := rand.New(rand.NewSource(42))
	services := []string{"api", "worker", "web", "cron", "gateway", "consumer", "scheduler", "admin", "sync", "export"}
	for i := 0; i < *nApps; i++ {
		as := appsets[i%len(appsets)]
		cl := clusters[r.Intn(len(clusters))]["name"].(string)
		svc := services[r.Intn(len(services))]
		name := fmt.Sprintf("%s-%s-%s-%04d", as, svc, cl, i)
		a := &app{Name: name, AppSet: as, Project: strings.Split(as, "-")[0], Cluster: cl, NS: as + "-" + svc,
			Repo: "https://github.com/acme/deploy.git", Path: "apps/" + as + "/" + svc, Sync: "Synced", Health: "Healthy",
			Phase: "Succeeded", OpMsg: "successfully synced (all tasks run)", RV: rv, Reconciled: time.Now(), Finished: time.Now().Add(-time.Duration(r.Intn(72*60)) * time.Minute)}
		if i%10 == 7 {
			a.AppSet = ""
		}
		switch x := r.Intn(1000); {
		case x < 12:
			a.Phase, a.Sync, a.OpMsg = "Failed", "OutOfSync", "one or more objects failed to apply, reason: Deployment.apps \""+svc+"\" is invalid: spec.template.spec.containers[0].image: Required value"
			a.FailedRes = []obj{{"group": "apps", "version": "v1", "kind": "Deployment", "namespace": a.NS, "name": svc, "status": "SyncFailed",
				"message": "Deployment.apps \"" + svc + "\" is invalid: spec.template.spec.containers[0].image: Required value"}}
		case x < 22:
			a.Health = "Degraded"
			a.Degraded = []obj{{"kind": "Pod", "name": svc + "-7d9f8b6c5d-x2k9p", "msg": "back-off 5m0s restarting failed container=app", "reason": "CrashLoopBackOff"}}
		case x < 27:
			a.Health = "Degraded"
			a.Degraded = []obj{{"kind": "Pod", "name": svc + "-5c6d7e8f9a-q8w7e", "msg": "Back-off pulling image \"ghcr.io/acme/" + svc + ":v2.3.1\"", "reason": "ImagePullBackOff"}}
		case x < 33:
			a.Sync, a.Health = "Unknown", "Unknown"
			a.Conditions = []obj{{"type": "ComparisonError", "message": "Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = authentication required: Repository not found."}}
		case x < 36:
			a.Phase, a.Retry, a.OpMsg = "Running", 3, "Retrying attempt #3 at 10:41AM: waiting for healthy state of apps/Deployment/"+svc
		case x < 80:
			a.Sync = "OutOfSync"
		case x < 90:
			a.Health = "Progressing"
		case x < 95:
			a.Conditions = []obj{{"type": "OrphanedResourceWarning", "message": "Application has 2 orphaned resources"}}
		}
		apps[name] = a
	}
}

func (a *app) toJSON() obj {
	cs := ""
	for _, c := range clusters {
		if c["name"] == a.Cluster {
			cs = c["server"].(string)
		}
	}
	meta := obj{"name": a.Name, "namespace": "argocd", "resourceVersion": fmt.Sprint(a.RV),
		"labels": obj{"team": a.Project, "env": a.Cluster}, "creationTimestamp": "2025-01-10T10:00:00Z"}
	if a.AppSet != "" {
		meta["ownerReferences"] = []obj{{"apiVersion": "argoproj.io/v1alpha1", "kind": "ApplicationSet", "name": a.AppSet}}
	}
	res := []obj{
		{"group": "apps", "version": "v1", "kind": "Deployment", "namespace": a.NS, "name": "app", "status": a.Sync},
		{"version": "v1", "kind": "Service", "namespace": a.NS, "name": "app", "status": "Synced"},
		{"version": "v1", "kind": "ConfigMap", "namespace": a.NS, "name": "app-config", "status": a.Sync},
		{"group": "networking.k8s.io", "version": "v1", "kind": "Ingress", "namespace": a.NS, "name": "app", "status": "Synced"},
	}
	op := obj{"phase": a.Phase, "message": a.OpMsg, "startedAt": a.Finished.Add(-30 * time.Second).Format(time.RFC3339), "retryCount": a.Retry}
	if a.Phase != "Running" {
		op["finishedAt"] = a.Finished.Format(time.RFC3339)
	}
	if len(a.FailedRes) > 0 {
		op["syncResult"] = obj{"revision": "9f8e7d6c5b4a39281706f5e4d3c2b1a098765432", "resources": a.FailedRes}
	}
	return obj{
		"metadata": meta,
		"spec": obj{"project": a.Project, "source": obj{"repoURL": a.Repo, "path": a.Path, "targetRevision": "main"},
			"destination": obj{"server": cs, "namespace": a.NS}, "syncPolicy": obj{"automated": obj{"prune": true, "selfHeal": true}}},
		"status": obj{
			"sync":           obj{"status": a.Sync, "revision": "9f8e7d6c5b4a39281706f5e4d3c2b1a098765432"},
			"health":         obj{"status": a.Health},
			"operationState": op, "conditions": a.Conditions, "resources": res,
			"reconciledAt": a.Reconciled.Format(time.RFC3339),
			"history": []obj{{"id": 1, "revision": "1a2b3c4d5e6f", "deployedAt": a.Finished.Add(-48 * time.Hour).Format(time.RFC3339)},
				{"id": 2, "revision": "9f8e7d6c5b4a", "deployedAt": a.Finished.Format(time.RFC3339)}},
		},
	}
}

func publish(a *app, typ string) {
	mu.Lock()
	rv++
	a.RV = rv
	a.Reconciled = time.Now()
	ev := obj{"result": obj{"type": typ, "application": a.toJSON()}}
	for ch := range subs {
		select {
		case ch <- ev:
		default:
		}
	}
	mu.Unlock()
}

// churn simulates a busy control plane.
func churn() {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	for range time.Tick(400 * time.Millisecond) {
		mu.RLock()
		var pick *app
		n := r.Intn(len(apps))
		for _, a := range apps {
			if n == 0 {
				pick = a
				break
			}
			n--
		}
		mu.RUnlock()
		if pick == nil {
			continue
		}
		mu.Lock()
		switch r.Intn(4) {
		case 0:
			if pick.Health == "Healthy" {
				pick.Health = "Progressing"
			} else if pick.Health == "Progressing" {
				pick.Health = "Healthy"
			}
		case 1:
			if pick.Sync == "Synced" && pick.Phase == "Succeeded" {
				pick.Sync = "OutOfSync"
			}
		default:
			pick.Finished = time.Now()
		}
		mu.Unlock()
		publish(pick, "MODIFIED")
	}
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}

func authed(r *http.Request) bool {
	tok := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
	tokenMu.Lock()
	defer tokenMu.Unlock()
	_, ok := tokens[tok]
	return ok
}

func issue(user string, ttl time.Duration) string {
	hdr := base64.RawURLEncoding.EncodeToString([]byte(`{"alg":"none"}`))
	body, _ := json.Marshal(obj{"sub": user, "exp": time.Now().Add(ttl).Unix(), "iat": time.Now().Unix(), "n": rand.Int()})
	tok := hdr + "." + base64.RawURLEncoding.EncodeToString(body) + ".sig"
	tokenMu.Lock()
	tokens[tok] = user
	tokenMu.Unlock()
	return tok
}

func main() {
	flag.Parse()
	gen()
	go churn()
	base := fmt.Sprintf("http://localhost:%d", *port)
	mux := http.NewServeMux()

	mux.HandleFunc("/api/version", func(w http.ResponseWriter, r *http.Request) { writeJSON(w, obj{"Version": "v3.1.0+mock"}) })
	mux.HandleFunc("/api/v1/settings", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, obj{"url": base, "dexConfig": obj{"connectors": []obj{{"name": "Mock SSO (" + *label + ")", "type": "oidc"}}}})
	})
	// --- fake Dex ---
	mux.HandleFunc("/api/dex/.well-known/openid-configuration", func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, obj{"issuer": base + "/api/dex", "authorization_endpoint": base + "/api/dex/auth", "token_endpoint": base + "/api/dex/token",
			"code_challenge_methods_supported": []string{"S256"}})
	})
	mux.HandleFunc("/api/dex/auth", func(w http.ResponseWriter, r *http.Request) {
		q := r.URL.Query()
		fmt.Fprintf(w, `<html><body style="font-family:sans-serif;padding:40px"><h2>Mock SSO — %s</h2>
<p>client_id=%s</p><a href="%s?code=mockcode&state=%s" style="font-size:18px">Sign in as dev@acme.io →</a></body></html>`,
			*label, q.Get("client_id"), q.Get("redirect_uri"), q.Get("state"))
	})
	mux.HandleFunc("/api/dex/token", func(w http.ResponseWriter, r *http.Request) {
		_ = r.ParseForm()
		if r.Form.Get("grant_type") == "authorization_code" && r.Form.Get("code_verifier") == "" {
			w.WriteHeader(400)
			writeJSON(w, obj{"error": "invalid_request", "error_description": "missing code_verifier"})
			return
		}
		writeJSON(w, obj{"id_token": issue("dev@acme.io", 2*time.Minute), "refresh_token": "mock-refresh", "token_type": "bearer"})
	})
	// --- auth ---
	mux.HandleFunc("/api/v1/session", func(w http.ResponseWriter, r *http.Request) {
		var b struct{ Username, Password string }
		_ = json.NewDecoder(r.Body).Decode(&b)
		if b.Username != "admin" || b.Password != "admin" {
			w.WriteHeader(401)
			writeJSON(w, obj{"error": "Invalid username or password", "message": "Invalid username or password"})
			return
		}
		writeJSON(w, obj{"token": issue("admin", time.Hour)})
	})
	mux.HandleFunc("/api/v1/session/userinfo", func(w http.ResponseWriter, r *http.Request) {
		if !authed(r) {
			writeJSON(w, obj{"loggedIn": false})
			return
		}
		tokenMu.Lock()
		u := tokens[strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")]
		tokenMu.Unlock()
		writeJSON(w, obj{"loggedIn": true, "username": u})
	})

	guard := func(h http.HandlerFunc) http.HandlerFunc {
		return func(w http.ResponseWriter, r *http.Request) {
			if !authed(r) {
				w.WriteHeader(401)
				writeJSON(w, obj{"error": "invalid session", "message": "invalid session: token has invalid claims: token is expired"})
				return
			}
			h(w, r)
		}
	}

	mux.HandleFunc("/api/v1/applications", guard(func(w http.ResponseWriter, r *http.Request) {
		mu.RLock()
		items := make([]obj, 0, len(apps))
		for _, a := range apps {
			items = append(items, a.toJSON())
		}
		v := rv
		mu.RUnlock()
		writeJSON(w, obj{"metadata": obj{"resourceVersion": fmt.Sprint(v)}, "items": items})
	}))
	mux.HandleFunc("/api/v1/stream/applications", guard(func(w http.ResponseWriter, r *http.Request) {
		fl, _ := w.(http.Flusher)
		ch := make(chan obj, 256)
		mu.Lock()
		subs[ch] = struct{}{}
		mu.Unlock()
		defer func() { mu.Lock(); delete(subs, ch); mu.Unlock() }()
		w.Header().Set("Content-Type", "application/json")
		fl.Flush()
		enc := json.NewEncoder(w)
		for {
			select {
			case <-r.Context().Done():
				return
			case ev := <-ch:
				_ = enc.Encode(ev)
				fl.Flush()
			}
		}
	}))
	mux.HandleFunc("/api/v1/applications/", guard(func(w http.ResponseWriter, r *http.Request) {
		parts := strings.Split(strings.TrimPrefix(r.URL.Path, "/api/v1/applications/"), "/")
		mu.RLock()
		a := apps[parts[0]]
		mu.RUnlock()
		if a == nil {
			w.WriteHeader(404)
			writeJSON(w, obj{"message": "application not found"})
			return
		}
		sub := strings.Join(parts[1:], "/")
		switch {
		case sub == "" && r.Method == http.MethodGet:
			if r.URL.Query().Get("refresh") != "" {
				go publish(a, "MODIFIED")
			}
			mu.RLock()
			j := a.toJSON()
			mu.RUnlock()
			writeJSON(w, j)
		case sub == "sync":
			if a.Conditions != nil && a.Conditions[0]["type"] == "ComparisonError" {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "error resolving repo revision: authentication required: Repository not found."})
				return
			}
			mu.Lock()
			a.Phase, a.OpMsg, a.Retry = "Running", "syncing", 0
			mu.Unlock()
			publish(a, "MODIFIED")
			go func() {
				time.Sleep(2 * time.Second)
				mu.Lock()
				if a.FailedRes == nil {
					a.Phase, a.Sync, a.OpMsg, a.Finished = "Succeeded", "Synced", "successfully synced (all tasks run)", time.Now()
				} else {
					a.Phase, a.OpMsg, a.Finished = "Failed", "one or more objects failed to apply", time.Now()
				}
				mu.Unlock()
				publish(a, "MODIFIED")
			}()
			writeJSON(w, a.toJSON())
		case sub == "operation" && r.Method == http.MethodDelete:
			mu.Lock()
			a.Phase, a.OpMsg, a.Finished = "Failed", "Operation terminated", time.Now()
			mu.Unlock()
			publish(a, "MODIFIED")
			writeJSON(w, obj{})
		case sub == "resource/actions/v2":
			var b map[string]any
			_ = json.NewDecoder(r.Body).Decode(&b)
			if b["action"] != "restart" {
				w.WriteHeader(400)
				writeJSON(w, obj{"message": "unknown action"})
				return
			}
			if a.Cluster == "legacy-dc" {
				w.WriteHeader(500)
				writeJSON(w, obj{"message": "failed to patch Deployment " + a.NS + "/app: the server has asked for the client to provide credentials"})
				return
			}
			writeJSON(w, obj{})
		case sub == "resource-tree":
			// Deployment -> ReplicaSet -> Pods, Service -> EndpointSlice, ConfigMap.
			ns := a.NS
			depH := a.Health
			if depH == "Unknown" {
				depH = "Healthy"
			}
			nodes := []obj{
				{"group": "apps", "version": "v1", "kind": "Deployment", "namespace": ns, "name": "app", "uid": "dep", "health": obj{"status": depH},
					"info": []obj{{"name": "Revision", "value": "Rev:4"}}, "images": []string{"ghcr.io/acme/app:v2.3.1"}},
				{"group": "apps", "version": "v1", "kind": "ReplicaSet", "namespace": ns, "name": "app-7d9f8b6c5d", "uid": "rs",
					"parentRefs": []obj{{"group": "apps", "kind": "Deployment", "namespace": ns, "name": "app", "uid": "dep"}},
					"health":     obj{"status": depH}, "info": []obj{{"name": "Revision", "value": "Rev:4"}}},
				{"group": "apps", "version": "v1", "kind": "ReplicaSet", "namespace": ns, "name": "app-5c6d7e8f9a", "uid": "rs-old",
					"parentRefs": []obj{{"group": "apps", "kind": "Deployment", "namespace": ns, "name": "app", "uid": "dep"}},
					"health":     obj{"status": "Healthy"}, "info": []obj{{"name": "Revision", "value": "Rev:3"}}},
				{"version": "v1", "kind": "Service", "namespace": ns, "name": "app", "uid": "svc", "health": obj{"status": "Healthy"}},
				{"group": "discovery.k8s.io", "version": "v1", "kind": "EndpointSlice", "namespace": ns, "name": "app-x7k2p", "uid": "eps",
					"parentRefs": []obj{{"kind": "Service", "namespace": ns, "name": "app", "uid": "svc"}}},
				{"version": "v1", "kind": "ConfigMap", "namespace": ns, "name": "app-config", "uid": "cm"},
				{"group": "networking.k8s.io", "version": "v1", "kind": "Ingress", "namespace": ns, "name": "app", "uid": "ing", "health": obj{"status": "Healthy"}},
			}
			for i, d := range a.Degraded {
				nodes = append(nodes, obj{"version": "v1", "kind": d["kind"], "namespace": ns, "name": d["name"], "uid": fmt.Sprint("bad", i),
					"parentRefs": []obj{{"group": "apps", "kind": "ReplicaSet", "namespace": ns, "name": "app-7d9f8b6c5d", "uid": "rs"}},
					"health":     obj{"status": "Degraded", "message": d["msg"]}, "info": []obj{{"name": "Status Reason", "value": d["reason"]}, {"name": "Containers", "value": "0/1"}, {"name": "Restart Count", "value": "17"}}})
			}
			for i := 0; i < 2; i++ {
				nodes = append(nodes, obj{"version": "v1", "kind": "Pod", "namespace": ns, "name": fmt.Sprintf("app-7d9f8b6c5d-ab1%dc", i), "uid": fmt.Sprint("pod", i),
					"parentRefs": []obj{{"group": "apps", "kind": "ReplicaSet", "namespace": ns, "name": "app-7d9f8b6c5d", "uid": "rs"}},
					"health":     obj{"status": "Healthy"}, "images": []string{"ghcr.io/acme/app:v2.3.1"},
					"info": []obj{{"name": "Status Reason", "value": "Running"}, {"name": "Containers", "value": "1/1"}, {"name": "Node", "value": "gke-pool-1-a1b2"}}})
			}
			writeJSON(w, obj{"nodes": nodes})
		default:
			w.WriteHeader(404)
			writeJSON(w, obj{"message": "not found: " + sub})
		}
	}))
	mux.HandleFunc("/api/v1/applicationsets", guard(func(w http.ResponseWriter, r *http.Request) {
		items := []obj{}
		for _, s := range appsets {
			st := obj{"conditions": []obj{{"type": "ErrorOccurred", "status": "False", "reason": "ApplicationSetUpToDate", "message": "Successfully generated parameters"}}}
			if s == "reporting" {
				st = obj{"conditions": []obj{{"type": "ErrorOccurred", "status": "True", "reason": "ApplicationGenerationFromParamsError",
					"message": "failed to execute go template {{.path.basename}}: template: :1:7: executing \"\" at <.path.basename>: map has no entry for key \"path\""}}}
			}
			items = append(items, obj{"metadata": obj{"name": s, "namespace": "argocd"}, "status": st})
		}
		writeJSON(w, obj{"items": items})
	}))
	mux.HandleFunc("/api/v1/clusters", guard(func(w http.ResponseWriter, r *http.Request) {
		items := []obj{}
		for _, c := range clusters {
			cs := obj{"status": "Successful"}
			if c["name"] == "legacy-dc" {
				cs = obj{"status": "Failed", "message": "Get \"https://legacy.k8s.example.com/version\": dial tcp 10.20.0.5:443: i/o timeout"}
			}
			items = append(items, obj{"server": c["server"], "name": c["name"], "connectionState": cs, "info": obj{"serverVersion": "1.31"}})
		}
		writeJSON(w, obj{"items": items})
	}))

	log.Printf("mock Argo CD %q on %s with %d apps (login admin/admin or SSO)", *label, base, len(apps))
	log.Fatal(http.ListenAndServe(fmt.Sprintf("127.0.0.1:%d", *port), mux))
}
