// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {argocd} from '../models';
import {main} from '../models';
import {config} from '../models';
import {kube} from '../models';
import {kubestore} from '../models';

export function AppEvents(arg1:string):Promise<Array<store.EventRow>>;

export function AppSetDetail(arg1:string):Promise<store.AppSetDetail>;

export function AppSetGuard(arg1:string):Promise<store.AppSetGuard>;

export function AppSets():Promise<Array<store.AppSetSummary>>;

export function AppSources(arg1:string):Promise<store.AppSources>;

export function AppSyncWindows(arg1:string):Promise<argocd.AppSyncWindows>;

export function AppYAML(arg1:string):Promise<string>;

export function Apps():Promise<Array<store.AppSummary>>;

export function ArgoConfig(arg1:string):Promise<store.ArgoConfig>;

export function CLIConfigPath():Promise<string>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function Clusters():Promise<Array<store.ClusterSummary>>;

export function Containers(arg1:string,arg2:argocd.ResourceAction):Promise<Array<string>>;

export function Contexts():Promise<Array<config.Context>>;

export function CreateApp(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function CreateToken(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function CronAction(arg1:string,arg2:string):Promise<string>;

export function Delete(arg1:Array<string>,arg2:store.DeleteOptions):Promise<store.ActionReport>;

export function DeleteAppSet(arg1:string):Promise<void>;

export function DeleteCluster(arg1:string,arg2:string):Promise<void>;

export function DeleteContext(arg1:string):Promise<void>;

export function DeleteProject(arg1:string,arg2:string):Promise<void>;

export function DeleteRepository(arg1:string,arg2:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:argocd.ResourceAction,arg3:boolean,arg4:boolean):Promise<void>;

export function DeleteToken(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Detail(arg1:string):Promise<store.AppDetail>;

export function Diff(arg1:string):Promise<Array<store.DiffItem>>;

export function History(arg1:string):Promise<Array<store.HistoryEntry>>;

export function ImageUpdater(arg1:string):Promise<store.ImageUpdater>;

export function ImportCLI():Promise<number>;

export function KDelete(arg1:string):Promise<void>;

export function KEvents(arg1:string):Promise<Array<kube.Event>>;

export function KObject(arg1:string):Promise<Record<string, any>>;

export function KObjects():Promise<Array<kubestore.Obj>>;

export function KPods(arg1:string):Promise<Array<kube.PodInfo>>;

export function KSaveYAML(arg1:string,arg2:string):Promise<void>;

export function KStartLogs(arg1:kubestore.LogRequest):Promise<string>;

export function KYAML(arg1:string):Promise<string>;

export function KubeContexts():Promise<Array<kubestore.ContextView>>;

export function KubeReconnect(arg1:string):Promise<void>;

export function KubeStatuses():Promise<Array<kubestore.ContextStatus>>;

export function KubeconfigPaths():Promise<Array<string>>;

export function LoginPassword(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function LoginSSO(arg1:string):Promise<void>;

export function LoginToken(arg1:string,arg2:string):Promise<void>;

export function Logout(arg1:string):Promise<void>;

export function NewAppTemplate(arg1:string):Promise<string>;

export function NotificationPrefs():Promise<main.NotifyPrefs>;

export function OpenInArgo(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PatchResourceYAML(arg1:string,arg2:argocd.ResourceAction,arg3:string):Promise<void>;

export function Prefs():Promise<config.Prefs>;

export function ProjectYAML(arg1:string,arg2:string):Promise<string>;

export function Reconnect(arg1:string):Promise<void>;

export function Refresh(arg1:Array<string>,arg2:boolean):Promise<store.ActionReport>;

export function ResourceActions(arg1:string,arg2:argocd.ResourceAction):Promise<Array<argocd.ActionDef>>;

export function ResourceEvents(arg1:string,arg2:argocd.ResourceAction,arg3:string):Promise<Array<store.EventRow>>;

export function ResourceYAML(arg1:string,arg2:argocd.ResourceAction):Promise<string>;

export function Restart(arg1:Array<string>):Promise<store.ActionReport>;

export function RestartPods(arg1:string):Promise<number>;

export function RestartResource(arg1:string,arg2:argocd.ResourceAction):Promise<void>;

export function Rollback(arg1:string,arg2:number,arg3:boolean,arg4:boolean):Promise<void>;

export function RolloutAction(arg1:string,arg2:string):Promise<void>;

export function RunAction(arg1:string,arg2:argocd.ResourceAction,arg3:string):Promise<void>;

export function SaveAppYAML(arg1:string,arg2:string):Promise<void>;

export function SaveContext(arg1:config.Context):Promise<config.Context>;

export function SaveProjectYAML(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveRepository(arg1:string,arg2:argocd.RepoInput,arg3:boolean):Promise<void>;

export function SaveSource(arg1:string,arg2:number,arg3:Record<string, any>):Promise<void>;

export function SetImageUpdater(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SetKubeContexts(arg1:Array<string>):Promise<void>;

export function SetNotificationPrefs(arg1:main.NotifyPrefs):Promise<void>;

export function SetPrefs(arg1:config.Prefs):Promise<void>;

export function SetSyncPolicy(arg1:Array<string>,arg2:store.SyncPolicy):Promise<store.ActionReport>;

export function SetUpdateCheck(arg1:boolean):Promise<void>;

export function StartLogs(arg1:string,arg2:store.LogRequest):Promise<string>;

export function StartTerminal(arg1:string,arg2:store.TerminalRequest):Promise<string>;

export function Statuses():Promise<Array<store.ContextStatus>>;

export function StopLogs(arg1:string):Promise<void>;

export function SubmitTemplate(arg1:string,arg2:Record<string, string>):Promise<string>;

export function Sync(arg1:Array<string>,arg2:argocd.SyncOptions):Promise<store.ActionReport>;

export function TermClose(arg1:string):Promise<void>;

export function TermInput(arg1:string,arg2:string):Promise<void>;

export function TermResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Terminate(arg1:Array<string>):Promise<store.ActionReport>;

export function TestContext(arg1:config.Context):Promise<string>;

export function TestNotification():Promise<void>;

export function UpdateCheckEnabled():Promise<boolean>;

export function UpdateClusterMeta(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<void>;

export function Version():Promise<string>;

export function WorkflowAction(arg1:string,arg2:string):Promise<string>;
