// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {argocd} from '../models';
import {config} from '../models';

export function AppSetDetail(arg1:string):Promise<store.AppSetDetail>;

export function AppSets():Promise<Array<store.AppSetSummary>>;

export function Apps():Promise<Array<store.AppSummary>>;

export function ArgoConfig(arg1:string):Promise<store.ArgoConfig>;

export function CLIConfigPath():Promise<string>;

export function Clusters():Promise<Array<store.ClusterSummary>>;

export function Containers(arg1:string,arg2:argocd.ResourceAction):Promise<Array<string>>;

export function Contexts():Promise<Array<config.Context>>;

export function Delete(arg1:Array<string>,arg2:store.DeleteOptions):Promise<store.ActionReport>;

export function DeleteAppSet(arg1:string):Promise<void>;

export function DeleteContext(arg1:string):Promise<void>;

export function Detail(arg1:string):Promise<store.AppDetail>;

export function History(arg1:string):Promise<Array<store.HistoryEntry>>;

export function ImportCLI():Promise<number>;

export function LoginPassword(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function LoginSSO(arg1:string):Promise<void>;

export function LoginToken(arg1:string,arg2:string):Promise<void>;

export function Logout(arg1:string):Promise<void>;

export function OpenInArgo(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Prefs():Promise<config.Prefs>;

export function Reconnect(arg1:string):Promise<void>;

export function Refresh(arg1:Array<string>,arg2:boolean):Promise<store.ActionReport>;

export function Restart(arg1:Array<string>):Promise<store.ActionReport>;

export function RestartResource(arg1:string,arg2:argocd.ResourceAction):Promise<void>;

export function Rollback(arg1:string,arg2:number,arg3:boolean,arg4:boolean):Promise<void>;

export function SaveContext(arg1:config.Context):Promise<config.Context>;

export function SetPrefs(arg1:config.Prefs):Promise<void>;

export function StartLogs(arg1:string,arg2:store.LogRequest):Promise<string>;

export function Statuses():Promise<Array<store.ContextStatus>>;

export function StopLogs(arg1:string):Promise<void>;

export function Sync(arg1:Array<string>,arg2:argocd.SyncOptions):Promise<store.ActionReport>;

export function Terminate(arg1:Array<string>):Promise<store.ActionReport>;

export function TestContext(arg1:config.Context):Promise<string>;
