// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppSets() {
  return window['go']['main']['App']['AppSets']();
}

export function Apps() {
  return window['go']['main']['App']['Apps']();
}

export function CLIConfigPath() {
  return window['go']['main']['App']['CLIConfigPath']();
}

export function Clusters() {
  return window['go']['main']['App']['Clusters']();
}

export function Contexts() {
  return window['go']['main']['App']['Contexts']();
}

export function DeleteContext(arg1) {
  return window['go']['main']['App']['DeleteContext'](arg1);
}

export function Detail(arg1) {
  return window['go']['main']['App']['Detail'](arg1);
}

export function ImportCLI() {
  return window['go']['main']['App']['ImportCLI']();
}

export function LoginPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoginPassword'](arg1, arg2, arg3, arg4);
}

export function LoginSSO(arg1) {
  return window['go']['main']['App']['LoginSSO'](arg1);
}

export function LoginToken(arg1, arg2) {
  return window['go']['main']['App']['LoginToken'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function OpenInArgo(arg1) {
  return window['go']['main']['App']['OpenInArgo'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Prefs() {
  return window['go']['main']['App']['Prefs']();
}

export function Reconnect(arg1) {
  return window['go']['main']['App']['Reconnect'](arg1);
}

export function Refresh(arg1, arg2) {
  return window['go']['main']['App']['Refresh'](arg1, arg2);
}

export function Restart(arg1) {
  return window['go']['main']['App']['Restart'](arg1);
}

export function RestartResource(arg1, arg2) {
  return window['go']['main']['App']['RestartResource'](arg1, arg2);
}

export function SaveContext(arg1) {
  return window['go']['main']['App']['SaveContext'](arg1);
}

export function SetPrefs(arg1) {
  return window['go']['main']['App']['SetPrefs'](arg1);
}

export function Statuses() {
  return window['go']['main']['App']['Statuses']();
}

export function Sync(arg1, arg2) {
  return window['go']['main']['App']['Sync'](arg1, arg2);
}

export function Terminate(arg1) {
  return window['go']['main']['App']['Terminate'](arg1);
}

export function TestContext(arg1) {
  return window['go']['main']['App']['TestContext'](arg1);
}
