// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppEvents(arg1) {
  return window['go']['main']['App']['AppEvents'](arg1);
}

export function AppSetDetail(arg1) {
  return window['go']['main']['App']['AppSetDetail'](arg1);
}

export function AppSetGuard(arg1) {
  return window['go']['main']['App']['AppSetGuard'](arg1);
}

export function AppSets() {
  return window['go']['main']['App']['AppSets']();
}

export function AppSources(arg1) {
  return window['go']['main']['App']['AppSources'](arg1);
}

export function AppYAML(arg1) {
  return window['go']['main']['App']['AppYAML'](arg1);
}

export function Apps() {
  return window['go']['main']['App']['Apps']();
}

export function ArgoConfig(arg1) {
  return window['go']['main']['App']['ArgoConfig'](arg1);
}

export function CLIConfigPath() {
  return window['go']['main']['App']['CLIConfigPath']();
}

export function Clusters() {
  return window['go']['main']['App']['Clusters']();
}

export function Containers(arg1, arg2) {
  return window['go']['main']['App']['Containers'](arg1, arg2);
}

export function Contexts() {
  return window['go']['main']['App']['Contexts']();
}

export function CronAction(arg1, arg2) {
  return window['go']['main']['App']['CronAction'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['main']['App']['Delete'](arg1, arg2);
}

export function DeleteAppSet(arg1) {
  return window['go']['main']['App']['DeleteAppSet'](arg1);
}

export function DeleteContext(arg1) {
  return window['go']['main']['App']['DeleteContext'](arg1);
}

export function DeleteResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteResource'](arg1, arg2, arg3, arg4);
}

export function Detail(arg1) {
  return window['go']['main']['App']['Detail'](arg1);
}

export function Diff(arg1) {
  return window['go']['main']['App']['Diff'](arg1);
}

export function History(arg1) {
  return window['go']['main']['App']['History'](arg1);
}

export function ImportCLI() {
  return window['go']['main']['App']['ImportCLI']();
}

export function KDelete(arg1) {
  return window['go']['main']['App']['KDelete'](arg1);
}

export function KEvents(arg1) {
  return window['go']['main']['App']['KEvents'](arg1);
}

export function KObject(arg1) {
  return window['go']['main']['App']['KObject'](arg1);
}

export function KObjects() {
  return window['go']['main']['App']['KObjects']();
}

export function KPods(arg1) {
  return window['go']['main']['App']['KPods'](arg1);
}

export function KSaveYAML(arg1, arg2) {
  return window['go']['main']['App']['KSaveYAML'](arg1, arg2);
}

export function KStartLogs(arg1) {
  return window['go']['main']['App']['KStartLogs'](arg1);
}

export function KYAML(arg1) {
  return window['go']['main']['App']['KYAML'](arg1);
}

export function KubeContexts() {
  return window['go']['main']['App']['KubeContexts']();
}

export function KubeReconnect(arg1) {
  return window['go']['main']['App']['KubeReconnect'](arg1);
}

export function KubeStatuses() {
  return window['go']['main']['App']['KubeStatuses']();
}

export function KubeconfigPaths() {
  return window['go']['main']['App']['KubeconfigPaths']();
}

export function LoginPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoginPassword'](arg1, arg2, arg3, arg4);
}

export function LoginSSO(arg1) {
  return window['go']['main']['App']['LoginSSO'](arg1);
}

export function LoginToken(arg1, arg2) {
  return window['go']['main']['App']['LoginToken'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function OpenInArgo(arg1) {
  return window['go']['main']['App']['OpenInArgo'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PatchResourceYAML(arg1, arg2, arg3) {
  return window['go']['main']['App']['PatchResourceYAML'](arg1, arg2, arg3);
}

export function Prefs() {
  return window['go']['main']['App']['Prefs']();
}

export function Reconnect(arg1) {
  return window['go']['main']['App']['Reconnect'](arg1);
}

export function Refresh(arg1, arg2) {
  return window['go']['main']['App']['Refresh'](arg1, arg2);
}

export function ResourceActions(arg1, arg2) {
  return window['go']['main']['App']['ResourceActions'](arg1, arg2);
}

export function ResourceEvents(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResourceEvents'](arg1, arg2, arg3);
}

export function ResourceYAML(arg1, arg2) {
  return window['go']['main']['App']['ResourceYAML'](arg1, arg2);
}

export function Restart(arg1) {
  return window['go']['main']['App']['Restart'](arg1);
}

export function RestartPods(arg1) {
  return window['go']['main']['App']['RestartPods'](arg1);
}

export function RestartResource(arg1, arg2) {
  return window['go']['main']['App']['RestartResource'](arg1, arg2);
}

export function Rollback(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Rollback'](arg1, arg2, arg3, arg4);
}

export function RolloutAction(arg1, arg2) {
  return window['go']['main']['App']['RolloutAction'](arg1, arg2);
}

export function RunAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunAction'](arg1, arg2, arg3);
}

export function SaveAppYAML(arg1, arg2) {
  return window['go']['main']['App']['SaveAppYAML'](arg1, arg2);
}

export function SaveContext(arg1) {
  return window['go']['main']['App']['SaveContext'](arg1);
}

export function SaveSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSource'](arg1, arg2, arg3);
}

export function SetKubeContexts(arg1) {
  return window['go']['main']['App']['SetKubeContexts'](arg1);
}

export function SetPrefs(arg1) {
  return window['go']['main']['App']['SetPrefs'](arg1);
}

export function SetSyncPolicy(arg1, arg2) {
  return window['go']['main']['App']['SetSyncPolicy'](arg1, arg2);
}

export function StartLogs(arg1, arg2) {
  return window['go']['main']['App']['StartLogs'](arg1, arg2);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2);
}

export function Statuses() {
  return window['go']['main']['App']['Statuses']();
}

export function StopLogs(arg1) {
  return window['go']['main']['App']['StopLogs'](arg1);
}

export function SubmitTemplate(arg1, arg2) {
  return window['go']['main']['App']['SubmitTemplate'](arg1, arg2);
}

export function Sync(arg1, arg2) {
  return window['go']['main']['App']['Sync'](arg1, arg2);
}

export function TermClose(arg1) {
  return window['go']['main']['App']['TermClose'](arg1);
}

export function TermInput(arg1, arg2) {
  return window['go']['main']['App']['TermInput'](arg1, arg2);
}

export function TermResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TermResize'](arg1, arg2, arg3);
}

export function Terminate(arg1) {
  return window['go']['main']['App']['Terminate'](arg1);
}

export function TestContext(arg1) {
  return window['go']['main']['App']['TestContext'](arg1);
}

export function WorkflowAction(arg1, arg2) {
  return window['go']['main']['App']['WorkflowAction'](arg1, arg2);
}
